Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    #Port Forward - Porta redirecionada do IP do Hospedeiro para a máquina virtual
    config.vm.network "forwarded_port", guest: 80, host: 8080
    
    
    #Private Network - Rede interna do virtualizador
    #config.vm.network "private_network", ip: "192.168.50.4"
    config.vm.network "private_network", type: "dhcp"

    #Public Network - Ip externo que a VM terá na rede da empresa.
    config.vm.network "public_network", ip: "192.168.1.142"
  end