---
- name: "Baixando arquivos do Wordpress"
  get_url:
      url: 'https://www.wordpress.org/latest.tar.gz'
      dest: '/tmp/wordpress.tar.gz'
  become: yes

- name: "Extraindo arquivo ZIP do Wordpress"
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes
  
- name: "Copiando arquivo WP-Config"
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "Ajustando arquivo WP-Config.php"
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - {regex: 'database_name_here', value: "{{ db_name }}"}
    - {regex: 'username_here', value: "{{ db_username }}"}
    - {regex: 'password_here', value: "{{ db_passwd }}"}
    - {regex: 'localhost', value: "{{ db_host_ip }}"}
  become: yes

- name: 'Configura Apache para servir o Wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
  - restart apache2