Vagrant.configure("2") do |config|
    
    #VM Ansible -192.168.1.25-
    config.vm.define "ansible" do |ansible|
        ansible.vm.box = "ubuntu/focal64"
        ansible.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "ansible"
        end
        ansible.vm.network "public_network", ip: "192.168.1.25"
        #Instalação do Ansible
        ansible.vm.provision "shell",
            inline: "apt update && \
                    add-apt-repository --yes --update ppa:ansible/ansible && \
                    apt install ansible --yes"
        #Gera uma nova key para acessar os ambientes
        ansible.vm.provision "shell",
            inline: "ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/ansible_key -q -N '' && \
                    cp /home/vagrant/.ssh/ansible_key.pub /vagrant/", privileged: false
        #Adicionar a key ao ssh.config
        ansible.vm.provision "shell",
            inline: "echo 'IdentityFile ~/.ssh/ansible_key' >> /etc/ssh/ssh_config && \
                    systemctl restart ssh"
    end
    
    # #VM Wordpress -192.168.1.35-
    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.box = "ubuntu/focal64"
        wordpress.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "wordpress"
        end
        wordpress.vm.network "public_network", ip: "192.168.1.35"
        wordpress.vm.provision "shell",
            inline: "cat /vagrant/ansible_key.pub >> .ssh/authorized_keys", privileged: false
    end
end