#Generate script to create 3 virtual boxes.
# 1 ansible controller / 1 mysql-server / 1 webserver 
# 

#VAR
$vm_box = "ubuntu/focal64"
$ansible_ip = "192.168.1.25"
$webserver_ip = "192.168.1.35"
$mysql_ip = '192.168.1.45'

Vagrant.configure("2") do |config|
    
    #VM Ansible
    config.vm.define "ansible" do |ansible|
        ansible.vm.box = $vm_box
        ansible.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "ansible"
        end
        #network
        ansible.vm.hostname = "ansible"
        ansible.vm.network "public_network", ip: $ansible_ip
        #Ansible install
        ansible.vm.provision "shell", inline: "apt update && 
                    add-apt-repository --yes --update ppa:ansible/ansible && \
                    apt install ansible --yes"
        #Generate a new key to access 
        ansible.vm.provision "shell",
            inline: "ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/ansible_key -q -N '' && \
                    cp /home/vagrant/.ssh/ansible_key.pub /vagrant/", privileged: false
        #Adicionar a key ao ssh.config
        ansible.vm.provision "shell", inline: "echo 'IdentityFile ~/.ssh/ansible_key' >> /etc/ssh/ssh_config && 
                    systemctl restart ssh"
    end
    
    # #VM Webserver
    config.vm.define "webserver" do |webserver|
        webserver.vm.box = $vm_box
        webserver.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "webserver"
        end
        #network
        webserver.vm.hostname = "webserver"
        webserver.vm.network "public_network", ip: $webserver_ip
        #scripts
        webserver.vm.provision "shell", inline: "apt update"
        webserver.vm.provision "shell", inline: "cat /vagrant/ansible_key.pub >> .ssh/authorized_keys", privileged: false
    end

    # #VM Mysql
    config.vm.define "mysql" do |mysql|
        mysql.vm.box = $vm_box
        mysql.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "mysql"
        end
        #network
        mysql.vm.hostname = "mysql"
        mysql.vm.network "public_network", ip: $mysql_ip
        #scripts
        mysql.vm.provision "shell", inline: "apt update"
        mysql.vm.provision "shell", inline: "cat /vagrant/ansible_key.pub >> .ssh/authorized_keys", privileged: false
    end

end