Vagrant.configure("2") do |config|
    
    #VM Ansible -192.168.1.25-
    config.vm.define "ansible" do |ansible|
        ansible.ssh.username = 'vagrant'
        ansible.ssh.password = 'vagrant'
        ansible.ssh.insert_key = false
        ansible.vm.box = "ubuntu/focal64"
        ansible.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.name = "ansible"
            
        end
        ansible.vm.network "public_network", ip: "192.168.1.25"
        # ansible.vm.provision "shell",
            # inline: "apt update && \
            #         sudo apt install software-properties-common && \
            #         sudo add-apt-repository --yes --update ppa:ansible/ansible && \
            #         sudo apt install ansible --yes"
        # ansible.vm.provision "shell",
        #     inline: "ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/ansible_key1 -q -N '' && \
        #             cp /home/vagrant/.ssh/ansible_key1.pub /vagrant/", privileged: false
    end
    
    # #VM Wordpress -192.168.1.35-
    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.box = "ubuntu/focal64"
        wordpress.ssh.username = 'vagrant'
        wordpress.ssh.password = '123456'
        wordpress.ssh.insert_key = false
        wordpress.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.name = "wordpress"
        end
        wordpress.vm.network "public_network", ip: "192.168.1.35"
        wordpress.vm.provision "shell",
            inline: "cat /vagrant/ansible_key1.pub >> .ssh/authorized_keys"
    end
end